package com.superwebservice.publictypes;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2014-02-06T12:36:33.080+01:00
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://www.superwebservice.com/publictypes", name = "Meteo")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Meteo {

    @WebResult(name = "deposerRequeteResponse", targetNamespace = "http://www.superwebservice.com/publictypes", partName = "deposerRequeteResponse")
    @WebMethod
    public java.lang.String deposerRequete(
        @WebParam(partName = "deposerRequete", name = "deposerRequete", targetNamespace = "http://www.superwebservice.com/publictypes")
        DeposerRequete deposerRequete
    );

    @WebResult(name = "obtenirSituationMeteoResponse", targetNamespace = "http://www.superwebservice.com/publictypes", partName = "obtenirSituationMeteoResponse")
    @WebMethod
    public ObtenirSituationMeteoResponse obtenirSituationMeteo(
        @WebParam(partName = "obtenirSituationMeteo", name = "obtenirSituationMeteo", targetNamespace = "http://www.superwebservice.com/publictypes")
        java.lang.String obtenirSituationMeteo
    );
}
