package com.superwebservice.publictypes;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2014-02-06T12:36:33.096+01:00
 * Generated source version: 2.7.0
 * 
 */
@WebServiceClient(name = "ServeurWeatherService", 
                  wsdlLocation = "http://localhost:8090/meteo?wsdl",
                  targetNamespace = "http://www.superwebservice.com/publictypes") 
public class ServeurWeatherService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.superwebservice.com/publictypes", "ServeurWeatherService");
    public final static QName MeteoPort = new QName("http://www.superwebservice.com/publictypes", "MeteoPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8090/meteo?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServeurWeatherService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8090/meteo?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServeurWeatherService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServeurWeatherService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServeurWeatherService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns Meteo
     */
    @WebEndpoint(name = "MeteoPort")
    public Meteo getMeteoPort() {
        return super.getPort(MeteoPort, Meteo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Meteo
     */
    @WebEndpoint(name = "MeteoPort")
    public Meteo getMeteoPort(WebServiceFeature... features) {
        return super.getPort(MeteoPort, Meteo.class, features);
    }

}
